### ISSUE TITLE
pubs fails with `TypeError: must be str, not dict` (`bibdata['journal']`)

### ISSUE THREAD

**Issue by beuerle** [pubs/pubs#128] opened 2018-03-18 15:28 UTC
Something broke along the last couple of commits (probably #127 ?). I didn't have time yet to look into it more closely, but here's the error I get for a simple `pubs list` with the current revision:

```python
$ pubs list
Traceback (most recent call last):
  File "/bin/pubs", line 11, in <module>
    load_entry_point('pubs==0.7.0', 'console_scripts', 'pubs')()
  File "/usr/lib/python3.6/site-packages/pubs/pubs_cmd.py", line 97, in execute
    args.func(conf, args)
  File "/usr/lib/python3.6/site-packages/pubs/commands/list_cmd.py", line 51, in command
    for p in papers))
  File "/usr/lib/python3.6/site-packages/pubs/commands/list_cmd.py", line 51, in <genexpr>
    for p in papers))
  File "/usr/lib/python3.6/site-packages/pubs/pretty.py", line 66, in paper_oneliner
    bibdesc = bib_oneliner(p.bibdata)
  File "/usr/lib/python3.6/site-packages/pubs/pretty.py", line 40, in bib_oneliner
    journal = ' ' + bibdata['journal']
TypeError: must be str, not dict
```

**Comment by benureau** [comment] 2018-03-19 01:43
I can reproduce it. I am on it.

**Comment by benureau** [comment] 2018-03-19 02:01
@beuerle: So, this is due to the cache not being up-to-date. The easiest way to resolve it is to go into your `pubs` directory and delete the `.cache` directory. We did not think about this, and none of our unit tests catches this situation.

I am closing this and opening #129 for a more permanent fix.

**Closed by benureau** 2018-03-19 02:01 UTC

**Comment by beuerle** [comment] 2018-03-19 08:00
Ah, yes. Should have thought about that. Thanks!
