### ISSUE TITLE
Bibliographic info not well imported from DOI

### ISSUE THREAD

**Issue by hinojojojo** [pubs/pubs#269] opened 2021-10-26 05:37 UTC
Hi
I have been using pubs now for about two years and has been great. I had a couple of months without importing new bibliography, but this week I have been importing a few new papers and found some weird performance, which happened in two computers, one running Arch Linux and another one running SalixOS, with pubs version 0.8.3
I have been importing with "pubs add -D someDOI -t someTag", e.g. "pubs add -D 10.1029/2020jg006090 -t someTag". This has been returning a citekey containing only the year (e.g. 2021b), and does not add the journal field. All other fields are well imported (e.g. author, title, publisher, year, number, volume). This happened with more than 20 papers I tried. A few months ago, an import basically returned everything perfectly, including journal and the citekey was made from the first author and the year.

Is this a behavior that could be affected by any software update (e.g. an update in Python packages) directly related to pubs? Most likely I installed pubs in both computers via pip using the stable version. Is this something that could be fixed by installing the git version?

**Comment by benureau** [comment] 2021-11-16 06:00
Hi @hinojojojo,

Sorry for the delay. I tried the command myself, and this is the intended behavior, as "2021" is the citekey provided by the imported DOI. Most of the time, the journals or website has provided an informative citekey, but in this instance, just the year is provided. There is a PR #209 to have the citekey auto-generated by pubs based on the first author and year, but it's not in master yet.

**Comment by benureau** [comment] 2021-11-21 18:44
Closing this issue, the work continues in #209.

**Closed by benureau** 2021-11-21 18:44 UTC
