### ISSUE TITLE
Prints ampersands in article titles as \&

### ISSUE THREAD

**Issue by yurivict** [pubs/pubs#190] opened 2019-01-21 02:58 UTC
For example:
```
[Wortzel_2011] Wortzel, I. and Seger, R. "The ERK Cascade: Distinct Functions within Various Subcellular Organelles" Genes \& Cancer (2011) [pdf] |
```
```DOI=10.1177/1947601911407328```

**Comment by benureau** [comment] 2019-01-21 04:06
Thanks! This is related to #161. I wonder if a simple search and replace approach would work.

**Comment by benureau** [comment] 2019-01-21 04:13
It should be tackled at the same time as #178, probably.

**Comment by omangin** [comment] 2019-01-24 05:36
This should be fixed on master. At least I cannot reproduce it.

@yurivict Which version of pubs are you using? Could you try with the latest version by installing with `pip install --upgrade git+https://github.com/pubs/pubs`?

**Comment by yurivict** [comment] 2019-01-24 05:45
Ok, thanks, I will wait for the next release.

**Closed** 2019-01-27 23:48 UTC
Labels: enhancement, reproduced
