### ISSUE TITLE
Add a citation for a web page

### ISSUE THREAD

**Issue by guillaumecherel** [pubs/pubs#81] opened 2017-07-20 14:19 UTC
How can I add a citation to a web page?

I tried to follow wikipedia's guidelines (https://en.wikipedia.org/w/index.php?title=Special:CiteThisPage&page=LaTeX&id=413720397). I ran `pubs add` and then typed in something like:

```
@misc{ wiki:xxx,
   author = "Wikipedia",
   title = "LaTeX --- Wikipedia{,} The Free Encyclopedia",
   year = "2011",
   url = "\url{https://en.wikipedia.org/w/index.php?title=LaTeX&oldid=413720397}",
   note = "[Online; accessed 20-July-2017]"
}
```
When I tried to edit the citation again, only the fields `author`, `title` and `year` were present. The others were lost.

**Comment by benureau** [comment] 2017-07-20 18:43
Indeed I was able to replicate your bug. The url is transformed into `link`, which may or may not be problematic (I'll have to look into it). But the note get swallowed, which is not expected. I'll get to the bottom of it.

**Comment by omangin** [comment] 2017-07-22 20:21
For the `url` to `link` issues, it's because we call bibtexparser with the `homogenize_fields=True` parameter (see [bibtexparser/bparser.py#L108-L117](https://github.com/sciunto-org/python-bibtexparser/blob/master/bibtexparser/bparser.py#L108-L117) and [bibtexparser/bparser.py#L241](https://github.com/sciunto-org/python-bibtexparser/blob/master/bibtexparser/bparser.py#L241)).

Considering that biblatex and natbib support the `url` field (according to [this](https://tex.stackexchange.com/questions/100782/add-a-hyperlink-in-bibtex) and [this](https://tex.stackexchange.com/questions/35977/how-to-add-a-url-to-a-latex-bibtex-file)), it should maybe be the default. That's something that we should report as an issue on [sciunto-org/python-bibtexparser](https://github.com/sciunto-org/python-bibtexparser).

**Comment by benureau** [comment] 2017-07-22 21:32
Hum... there are two things then:
* should `url` be changed to `link`? Possibly not. 
* extraneous fields (such as `notes` here) should not disappear without some kind of warning and/or confirmation from the user.

**Comment by omangin** [comment] 2017-07-29 19:21
I've just opened an [issue on bibtexparser](https://sciunto-org/python-bibtexparser/issues/171) for the `url` part.

I cannot reproduce the issue with the notes, though. @guillaumecherel, what versions of _python_, _bibtexparser_, and _pubs_ are you using?

**Comment by omangin** [comment] 2017-08-01 15:26
So, the `url` issue is now fixed upstream (sciunto-org/python-bibtexparser/pull/173).

Since I cannot reproduce the `note` issue with the current versions of pubs and [python-bibtexparser](http://github.com/sciunto-org/python-bibtexparser), I'll close the issue. @guillaumecherel, feel free to reopen it if you still experience the problem after updating both software from their latest git versions.

**Comment by benureau** [comment] 2017-08-01 18:28
I can reproduce the note issue, with bibtexparser 0.6.2, on macOS 10.12.6, python 3.6.1, with the latest version of pubs. I reopened the issue as a result. I'll look into it.

**Comment by omangin** [comment] 2017-08-01 20:05
Indeed, the bug is there for v0.6.2 of bibtexparser but has been fixed since then. It's an upstream bug anyway. I believe we should close this issue and eventually update the dependency to bibtexparser to require at least v0.7.0 when it's out…

**Comment by benureau** [comment] 2017-08-01 22:09
Ok, good for me.
@guillaumecherel: So to entirely fix the problem you need to install the latest development version of bibtexparser.

**Closed by benureau** 2017-08-01 22:09 UTC
Labels: bug, critical
